### ISSUE TITLE
This is a bad idea...

### ISSUE THREAD

**Issue by pidupuis** [slashsBin/styleguide-git-commit-message#21]
What I'm going to say is my opinion and only mine.

# This is a bad idea...
 - You lost readability of your commits in environments where emojis are not readable, which represents a lot of environments!
 - Readers must learn the meaning of an emoji instead of just reading a more-efficient keyword.

# ... full of bad ideas
- Not only you have to learn the meaning of the emojis, but it changes depending on the tools !
````
🐘 	:elephant: 	PostgreSQL Database specific (Migrations, Scripts, Extensions, ...)
🐬 	:dolphin: 	MySQL Database specific (Migrations, Scripts, Extensions, ...)
🍃 	:leaves: 	MongoDB Database specific (Migrations, Scripts, Extensions, ...)
🏦 	:bank: 	        Generic Database specific (Migrations, Scripts, Extensions, ...)
🐳 	:whale: 	Docker Configuration
````
- If it is not enough, you encourage users to extend the lists!
- You force to add _at least_ one emoji, which means that you think about putting plenty of them, which takes a lot of place if not translated!
````
:emoji1: :emoji2: Subject
````
- There are some contradictions in your guide:
```
    All WIP(Work In Progress) Commits MUST have the WIP Emoji(see below).
    ...
    All WIP Commits Should be Avoided!.
```
- While the WIP commit is obviously a residual mistake, I should mention that you authorize to commit bugs!!
````
🐛 	:bug: 	when reporting a bug, with @FIXMEComment Tag
````

I thus think one should not follow this guideline, or at least not in its current state.

**Comment by lucadevitis-msm** [comment]
Let me get this straight, you opened an issue on a project to express your opinions on why people shouldn't use this project. Couldn't you just avoid to use it and write a blog post in your blog to express your opinions? Open a project in your space to offer an alternative, seems another sensible Idea. This issue looks more like a publicity stunt, or an attempt to troll a simple good effort on improoving team comunication by getting the best out of our tool, includin git commit messages.

**Comment by pidupuis** [comment]
You seem offended and I apologize for that. But you are wrong about my motives.

This is not just about opinion. I also took the time to list some ways of improvement despite the fact that I will not use your guide. I'm pretty sure that's what issues are for...
