### ISSUE TITLE
Chrome extension

### ISSUE THREAD

**Issue by louisgrasset** [slashsBin/styleguide-git-commit-message#22]
I developed this chrome extension (https://gitlab.com/louisgrasset/git-moji).
I'll update it following your repository.
What do you think about it?

**Comment by slashsbin** [comment]
That's really nice!
I've added it to [Tools section](https://github.com/slashsBin/styleguide-git-commit-message/blob/master/README.md#tools).
Thank you. 💟

**Comment by ykh** [comment]
@louisgrasset It would be nice if edit former repository url

**Comment by slashsbin** [comment]
The Repository is moved from github to gitlab here: https://gitlab.com/louisgrasset/git-moji.
Have fun!

**Comment by louisgrasset** [comment]
@ykh done :+1:
