### ISSUE TITLE
Emoji for Refactoring?

### ISSUE THREAD

**Issue by ykh** [slashsBin/styleguide-git-commit-message#25]
Hi Marine :D
Which Emoji It's Suitable for Refactoring Code (Brand, Names, ... Refactor)? (Is this :art: yet?)

**Comment by slashsbin** [comment]
Hi templar! :D
Refactoring Code is kind of a big concept that covers many aspects of a app/code structure, but for the sake of your answer, I think a good choice is :art: when changes are only UI specific and :tractor: when changes are mainly files/dir/class/namespace structure. They can be used together too.

If refactoring is causing incompatible changes: :zap: is a better choice; but keep in mind that major changes to the code structure are usually not a refactor anymore.

**Comment by andry81** [comment]
> Which Emoji It's Suitable for Refactoring Code (Brand, Names, ... Refactor)? (Is this 🎨 yet?)

Just was searching and have found this issue.
For myself I've found :twisted_rightwards_arrows: as more suitable for a refactor icon.
Used here: https://gist.github.com/andry81/d278e6d129ca1af326eafb67470a2ae3

**Comment by ykh** [comment]
@andry81 
Actually, I prefer to use 🔀 for "Merging" operations, it's more reasonable to me.
Although all of these are kind of conventions! So, feel free to use any emojis for any cases you want. 😄

**Comment by andry81** [comment]
@ykh 
> Actually, I prefer to use 🔀 for "Merging" operations, it's more reasonable to me.

The GitExtensions, for example, used another emoji for that: ♏ or `&#9807;`
