### ISSUE TITLE
I Can Not Load 'ghit.me' Image

### ISSUE THREAD

**Issue by ykh** [slashsBin/styleguide-git-commit-message#31]
Well, I'm walk around here today ;)
![404-image](https://user-images.githubusercontent.com/2290912/43356664-204493e2-928a-11e8-8ba2-72257510c231.png)
It happens just for me? (I even tried proxy)

**Comment by slashsbin** [comment]
Seems like https://ghit.me/ is down!
I'm gonna check on it later.

**Comment by slashsbin** [comment]
Yep it's down, removed it from code.
